apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "XO7xbsZ6/13YUgmhluNMDky9c7NmqoPxVYvuvwgZLVmBQ9zSyAnQ3R6/p+rjbMeH\nfG1rhLh0P4jMQ5+KfcR3oDQLJFi7tavdL9mp91XkzOh2l7lJ6KzKn9dKLse2qRG4\nsnt7KVGFNkuICH8rKSQDDax/nAKSZaD+nMPx/d5Oics="
